name: Add-In
on:
  push:
    branches:
      - main
      - develop
    paths: &paths
      - 'projects/addin/**'
      - 'tasks/**'
      - 'manifest.xml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cve-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: version
      - uses: OWASP/cve-lite-cli@v1
        with:
          node-version: ${{ steps.version.outputs.version }}
          verbose: 'true'
          fail-on: 'critical'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: node-version
      - uses: ./.github/actions/prepare-node
        with:
          version: ${{ steps.node-version.outputs.version }}
      - run: npm run lint:addin

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: node-version
      - uses: ./.github/actions/prepare-node
        with:
          version: ${{ steps.node-version.outputs.version }}
      - run: npm run test:addin

  build-and-deploy-addin:
    name: Build & Deploy AddIn
    runs-on: ubuntu-latest
    needs:
      - cve-check
      - lint
      - test
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: node-version
      - uses: ./.github/actions/prepare-node
        with:
          version: ${{ steps.node-version.outputs.version }}
          run-install: 'false'
      - name: Read version from package.json
        id: read_version
        if: github.ref == 'refs/heads/main'
        uses: ActionsTools/read-json-action@main
        with:
          file_path: package.json
          prop_path: version
      - name: Set version
        id: version
        run: echo "value=${{ steps.read_version.outputs.value || 'develop' }}" >> $GITHUB_OUTPUT
      - run: npm ci
      - run: npm run write-version-file
        env:
          APP_VERSION: ${{ steps.version.outputs.value }}
      - run: npm run build
        env:
          BASE_HREF: /addin/${{steps.version.outputs.value}}/
      - run: npx ng test addin --no-watch
      - run: npm run prepare-deployment
        env:
          APP_VERSION: ${{ steps.version.outputs.value }}
      - uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        if: github.event_name != 'pull_request'
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/addin/browser/
          server-dir: addin/${{steps.version.outputs.value}}/
          protocol: ftp
      - uses: actions/upload-artifact@v6
        if: github.event_name != 'pull_request'
        with:
          name: manifest
          path: dist/addin/browser/manifest.xml
          if-no-files-found: error
