name: Website
on:
  push:
    branches:
      - main
    paths: &paths
      - 'projects/website/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths: *paths
  issues:
  issue_comment:
  schedule:
    - cron: 0 0 * * *

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cve-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: version
      - uses: OWASP/cve-lite-cli@v1
        with:
          node-version: ${{ steps.version.outputs.version }}
          verbose: 'true'
          fail-on: 'critical'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: node-version
      - uses: ./.github/actions/prepare-node
        with:
          version: ${{ steps.node-version.outputs.version }}
      - run: npm run lint:website

  build-and-deploy-website:
    name: Build & Deploy Website
    runs-on: ubuntu-latest
    needs:
      - cve-check
      - lint
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: version
      - uses: ./.github/actions/prepare-node
        with:
          version: ${{ steps.version.outputs.version }}
      - run: npm run build:website
        env:
          LEHRGRAPHT_WEBSITE_GITHUB_TOKEN: ${{ secrets.LEHRGRAPHT_WEBSITE_GITHUB_TOKEN }}
      - run: npm run prepare-deployment
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        if: github.event_name != 'pull_request'
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/website/browser/
          server-dir: /
          protocol: ftp
          exclude: |
            addin/**
